export const CERTIFICATE_ROUTE_PARITY = {
  readPermission: 'read:certificates',
  removed: [
    'PATCH /certificates/:id',
    'DELETE /certificates/:id',
    'POST /certificates/:id/key',
    'GET /certificates/compliance',
    'GET /certificates/lint/status',
    'GET /certificates/:id/lint',
    'POST /certificates/:id/submit-ct',
  ],
  notImplemented: [
    'POST /certificates',
    'POST /certificates/:id/revoke',
    'POST /certificates/:id/unhold',
    'POST /certificates/:id/renew',
    'POST /certificates/:id/export',
    'POST /certificates/export',
    'POST /certificates/import',
    'POST /certificates/bulk/:operation',
    'POST /certificates/bulk/revoke',
    'POST /certificates/bulk/renew',
    'POST /certificates/bulk/delete',
    'POST /certificates/bulk/export',
  ],
} as const;
